-- -----------------------------------------------------
-- Table ITEMAVAL
-- -----------------------------------------------------
CREATE  TABLE ITEMAVAL (
  ID_ITEMAVAL NUMERIC(7) NOT NULL ,
  ENUN VARCHAR(100) NOT NULL ,
  COMENTARIO VARCHAR(100) DEFAULT NULL ,
  PRIMARY KEY (ID_ITEMAVAL) );


-- -----------------------------------------------------
-- Table PROVA
-- -----------------------------------------------------
CREATE  TABLE PROVA (
  ID_PROVA NUMERIC(7) NOT NULL ,
  ABERTA NUMERIC(1) NOT NULL ,
  NOME_PROF VARCHAR(50) NOT NULL ,
  QT_QUESTOES NUMERIC(7) NOT NULL ,
  HASH VARCHAR(50) NOT NULL ,
  PRIMARY KEY (ID_PROVA) );


-- -----------------------------------------------------
-- Table ALTERNATIVAS
-- -----------------------------------------------------
CREATE  TABLE ALTERNATIVAS (
  ID_ITEMAVAL NUMERIC(7) NOT NULL ,
  SQ_ALTERNATIVA NUMERIC(7) NOT NULL ,
  TEXTO VARCHAR(100) NOT NULL ,
  CORRETA NUMERIC(1) NOT NULL ,
  PRIMARY KEY (ID_ITEMAVAL, SQ_ALTERNATIVA) ,
  CONSTRAINT fk_ALTERNATIVAS_1
    FOREIGN KEY (ID_ITEMAVAL )
    REFERENCES ITEMAVAL (ID_ITEMAVAL )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX fk_ALTERNATIVAS_1 ON ALTERNATIVAS (ID_ITEMAVAL ASC) ;


-- -----------------------------------------------------
-- Table CATEGORIA
-- -----------------------------------------------------
CREATE  TABLE CATEGORIA (
  ID_CATEGORIA NUMERIC(7) NOT NULL ,
  NOME_CAT VARCHAR(45) NOT NULL ,
  PRIMARY KEY (ID_CATEGORIA) );


-- -----------------------------------------------------
-- Table ITEMAVAL_CATEGORIA
-- -----------------------------------------------------
CREATE  TABLE ITEMAVAL_CATEGORIA (
  ID_ITEMAVAL NUMERIC(7) NOT NULL ,
  ID_CATEGORIA NUMERIC(7) NOT NULL ,
  PRIMARY KEY (ID_ITEMAVAL, ID_CATEGORIA) ,
  CONSTRAINT fk_ITEMAVAL_CATEGORIA_1
    FOREIGN KEY (ID_ITEMAVAL )
    REFERENCES ITEMAVAL (ID_ITEMAVAL )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ITEMAVAL_CATEGORIA_2
    FOREIGN KEY (ID_CATEGORIA )
    REFERENCES CATEGORIA (ID_CATEGORIA )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX fk_ITEMAVAL_CATEGORIA_1 ON ITEMAVAL_CATEGORIA (ID_ITEMAVAL ASC) ;

CREATE INDEX fk_ITEMAVAL_CATEGORIA_2 ON ITEMAVAL_CATEGORIA (ID_CATEGORIA ASC) ;


-- -----------------------------------------------------
-- Table PROVA_CATEGORIA
-- -----------------------------------------------------
CREATE  TABLE PROVA_CATEGORIA (
  ID_CATEGORIA NUMERIC(7) NOT NULL ,
  ID_PROVA NUMERIC(7) NOT NULL ,
  PRIMARY KEY (ID_CATEGORIA, ID_PROVA) ,
  CONSTRAINT fk_PROVA_CATEGORIA_1
    FOREIGN KEY (ID_CATEGORIA )
    REFERENCES CATEGORIA (ID_CATEGORIA )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PROVA_CATEGORIA_2
    FOREIGN KEY (ID_PROVA )
    REFERENCES PROVA (ID_PROVA )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX fk_PROVA_CATEGORIA_1 ON PROVA_CATEGORIA (ID_CATEGORIA ASC) ;

CREATE INDEX fk_PROVA_CATEGORIA_2 ON PROVA_CATEGORIA (ID_PROVA ASC) ;


-- -----------------------------------------------------
-- Table ALUNOS
-- -----------------------------------------------------
CREATE  TABLE ALUNOS (
  ID_ALUNO NUMERIC(7) NOT NULL ,
  NOME_ALUNO VARCHAR(50) NOT NULL ,
  PRIMARY KEY (ID_ALUNO) );


-- -----------------------------------------------------
-- Table RESPOSTAS
-- -----------------------------------------------------
CREATE  TABLE RESPOSTAS (
  ID_PROVA NUMERIC(7) NOT NULL ,
  ID_ITEMAVAL NUMERIC(7) NOT NULL ,
  ALTERNATIVA_MARCADA NUMERIC(7) NOT NULL ,
  ID_ALUNO NUMERIC(7) NOT NULL ,
  PRIMARY KEY (ID_PROVA, ID_ITEMAVAL) ,
  CONSTRAINT fk_RESPOSTAS_1
    FOREIGN KEY (ID_PROVA )
    REFERENCES PROVA (ID_PROVA )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_RESPOSTAS_2
    FOREIGN KEY (ID_ITEMAVAL )
    REFERENCES ITEMAVAL (ID_ITEMAVAL )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_RESPOSTAS_3
    FOREIGN KEY (ID_ALUNO )
    REFERENCES ALUNOS (ID_ALUNO )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX fk_RESPOSTAS_1 ON RESPOSTAS (ID_PROVA ASC) ;

CREATE INDEX fk_RESPOSTAS_2 ON RESPOSTAS (ID_ITEMAVAL ASC) ;

CREATE INDEX fk_RESPOSTAS_3 ON RESPOSTAS (ID_ALUNO ASC) ;
