/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Negocio.Alternativa;
import Negocio.Categoria;
import Negocio.DAOException;
import Negocio.ItemAval;
import Negocio.SistemaFachada;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Ildevana
 */
public class CadastroItemAval extends javax.swing.JDialog {

    private final CategoriaController cControl;
    private final ItemAvaliacaoController iControl;

    /**
     * Creates new form CadastroItemAval
     *
     * @param parent
     * @param modal
     */
    public CadastroItemAval(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        cControl = new CategoriaController();
        iControl = new ItemAvaliacaoController();
        initComponents();
        //pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        corretaGrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtEnumciado = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        lstBaseCat = new javax.swing.JList();
        jScrollPane10 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnAddAll = new javax.swing.JButton();
        btnRemoveAll = new javax.swing.JButton();
        btnAddCat = new javax.swing.JButton();
        btnRemCat = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rdAlt1 = new javax.swing.JRadioButton();
        rdAlt2 = new javax.swing.JRadioButton();
        rdAlt3 = new javax.swing.JRadioButton();
        rdAlt4 = new javax.swing.JRadioButton();
        rdAlt5 = new javax.swing.JRadioButton();
        txtAlt1 = new javax.swing.JTextField();
        txtAlt2 = new javax.swing.JTextField();
        txtAlt3 = new javax.swing.JTextField();
        txtAlt4 = new javax.swing.JTextField();
        txtAlt5 = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Enumciado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane2.setViewportView(txtComentario);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 140, 170));

        jScrollPane8.setViewportView(txtEnumciado);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 460, 70));

        lstBaseCat.setModel(cControl.getListModel());
        jScrollPane9.setViewportView(lstBaseCat);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 120, 170));

        lstCategorias.setModel(new ListCategoriaModel());
        jScrollPane10.setViewportView(lstCategorias);

        getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 120, 170));

        jLabel2.setText("Alternativas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setText("Correta");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        jLabel4.setText("Comentário");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, -1));

        btnAddAll.setText(">>");
        btnAddAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 50, -1));

        btnRemoveAll.setText("<<");
        btnRemoveAll.setToolTipText("");
        btnRemoveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 50, -1));

        btnAddCat.setText(">");
        btnAddCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCatActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 50, -1));

        btnRemCat.setText("<");
        btnRemCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemCatActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 50, -1));

        jLabel5.setText("Categorias");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        corretaGrp.add(rdAlt1);
        rdAlt1.setSelected(true);
        rdAlt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAlt1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdAlt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        corretaGrp.add(rdAlt2);
        getContentPane().add(rdAlt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        corretaGrp.add(rdAlt3);
        getContentPane().add(rdAlt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        corretaGrp.add(rdAlt4);
        getContentPane().add(rdAlt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        corretaGrp.add(rdAlt5);
        rdAlt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAlt5ActionPerformed(evt);
            }
        });
        getContentPane().add(rdAlt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));
        getContentPane().add(txtAlt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 420, 20));
        getContentPane().add(txtAlt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 420, 20));
        getContentPane().add(txtAlt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 420, 20));
        getContentPane().add(txtAlt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 420, 20));
        getContentPane().add(txtAlt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 420, 20));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, -1, 510));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 470, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdAlt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAlt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAlt1ActionPerformed

    private void rdAlt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAlt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAlt5ActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            String txt;
            boolean crt;
            String enu = txtEnumciado.getText();
            String com = txtComentario.getText();
            List<Alternativa> alts = new ArrayList<>(5);

            txt = txtAlt1.getText();
            crt = rdAlt1.isSelected();
            alts.add(new Alternativa(0, 0, txt, crt));

            txt = txtAlt2.getText();
            crt = rdAlt2.isSelected();
            alts.add(new Alternativa(0, 0, txt, crt));

            txt = txtAlt3.getText();
            crt = rdAlt3.isSelected();
            alts.add(new Alternativa(0, 0, txt, crt));

            txt = txtAlt4.getText();
            crt = rdAlt4.isSelected();
            alts.add(new Alternativa(0, 0, txt, crt));

            txt = txtAlt5.getText();
            crt = rdAlt5.isSelected();
            alts.add(new Alternativa(0, 0, txt, crt));

            List<Categoria> cats = ((ListCategoriaModel) lstCategorias.getModel()).getLista();
            iControl.inserirItem(enu, com, alts, cats);
            JOptionPane.showMessageDialog(null, "Item cadastrado com sucesso!", "Error", JOptionPane.INFORMATION_MESSAGE);
            initComponents();
        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAddAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAllActionPerformed
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        List<Categoria> cats = m1.getLista();
        m2.addAll(cats);
        m1.removeAll(cats);
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnAddAllActionPerformed

    private void btnRemoveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAllActionPerformed
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        List<Categoria> cats = m2.getLista();
        m1.addAll(cats);
        m2.removeAll(cats);
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnRemoveAllActionPerformed

    private void btnAddCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCatActionPerformed
        List selecteds = lstBaseCat.getSelectedValuesList();
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        for (Object object : selecteds) {
            String[] s = object.toString().split("-");
            Categoria c = new Categoria(Integer.parseInt(s[0].trim()), s[1].trim());
            m1.remove(c);
            m2.add(c);
        }
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnAddCatActionPerformed

    private void btnRemCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemCatActionPerformed
        List selecteds = lstCategorias.getSelectedValuesList();
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        for (Object object : selecteds) {
            String[] s = object.toString().split("-");
            Categoria c = new Categoria(Integer.parseInt(s[0].trim()), s[1].trim());
            m1.add(c);
            m2.remove(c);
        }
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnRemCatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAll;
    private javax.swing.JButton btnAddCat;
    private javax.swing.JButton btnRemCat;
    private javax.swing.JButton btnRemoveAll;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup corretaGrp;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList lstBaseCat;
    private javax.swing.JList lstCategorias;
    private javax.swing.JRadioButton rdAlt1;
    private javax.swing.JRadioButton rdAlt2;
    private javax.swing.JRadioButton rdAlt3;
    private javax.swing.JRadioButton rdAlt4;
    private javax.swing.JRadioButton rdAlt5;
    private javax.swing.JTextField txtAlt1;
    private javax.swing.JTextField txtAlt2;
    private javax.swing.JTextField txtAlt3;
    private javax.swing.JTextField txtAlt4;
    private javax.swing.JTextField txtAlt5;
    private javax.swing.JTextPane txtComentario;
    private javax.swing.JTextPane txtEnumciado;
    // End of variables declaration//GEN-END:variables
}
