/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Negocio.Categoria;
import Negocio.DAOException;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author lasaro
 */
public class CadastrarProva extends javax.swing.JDialog {

    private ProvaController pControl;
    private CategoriaController cControl;

    /**
     * Creates new form CadastrarProva
     */
    public CadastrarProva(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pControl = new ProvaController();
        cControl = new CategoriaController();
        initComponents();
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoProva = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        lstBaseCat = new javax.swing.JList();
        btnAddCat = new javax.swing.JButton();
        btnRemCat = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        rdAberta = new javax.swing.JRadioButton();
        rdFechada = new javax.swing.JRadioButton();
        jButton7 = new javax.swing.JButton();
        btnAddAll = new javax.swing.JButton();
        btnRemoveAll = new javax.swing.JButton();
        txtNomeProf = new javax.swing.JTextField();
        txtQtdQuestoes = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Nome Professor:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel4.setText("Nº de Questoes:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel3.setText("Selecionar Categorias:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lstBaseCat.setModel(cControl.getListModel());
        jScrollPane9.setViewportView(lstBaseCat);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 170, 190));

        btnAddCat.setText(">");
        btnAddCat.setToolTipText("");
        btnAddCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCatActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 60, -1));

        btnRemCat.setText("<");
        btnRemCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemCatActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 60, -1));

        lstCategorias.setModel(new ListCategoriaModel());
        jScrollPane6.setViewportView(lstCategorias);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 170, 190));

        jLabel5.setText("Selecionar tipo de Prova:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        tipoProva.add(rdAberta);
        rdAberta.setSelected(true);
        rdAberta.setText("Aberta");
        rdAberta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAbertaActionPerformed(evt);
            }
        });
        getContentPane().add(rdAberta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 20));

        tipoProva.add(rdFechada);
        rdFechada.setText("Fechada");
        getContentPane().add(rdFechada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, 20));

        jButton7.setText("Salvar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 70, -1));

        btnAddAll.setText(">>");
        btnAddAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 60, -1));

        btnRemoveAll.setText("<<");
        btnRemoveAll.setToolTipText("");
        btnRemoveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 60, -1));
        getContentPane().add(txtNomeProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 280, 20));
        getContentPane().add(txtQtdQuestoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 40, 20));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCatActionPerformed
        List selecteds = lstBaseCat.getSelectedValuesList();
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        for (Object object : selecteds) {
            String[] s = object.toString().split("-");
            Categoria c = new Categoria(Integer.parseInt(s[0].trim()), s[1].trim());
            m1.remove(c);
            m2.add(c);
        }
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnAddCatActionPerformed

    private void rdAbertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAbertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdAbertaActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            ListCategoriaModel list = (ListCategoriaModel) lstCategorias.getModel();
            List<Categoria> listC = list.getLista();
            String nome = txtNomeProf.getText();
            int num = Integer.parseInt(txtQtdQuestoes.getText());
            boolean ab = rdAberta.isSelected();

            String hash = pControl.inserir(listC, nome, num, ab);
            String msg = "Prova salva com sucesso!";
            if (!ab) {
                msg += "\nHash da prova: " + hash;
            }
            JOptionPane.showMessageDialog(null, msg, "Info", JOptionPane.INFORMATION_MESSAGE);
        } catch (NumberFormatException | DAOException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnRemCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemCatActionPerformed
        List selecteds = lstCategorias.getSelectedValuesList();
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        for (Object object : selecteds) {
            String[] s = object.toString().split("-");
            Categoria c = new Categoria(Integer.parseInt(s[0].trim()), s[1].trim());
            m1.add(c);
            m2.remove(c);
        }
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnRemCatActionPerformed

    private void btnAddAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAllActionPerformed
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        List<Categoria> cats = m1.getLista();
        m2.addAll(cats);
        m1.removeAll(cats);
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnAddAllActionPerformed

    private void btnRemoveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAllActionPerformed
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        List<Categoria> cats = m2.getLista();
        m1.addAll(cats);
        m2.removeAll(cats);
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnRemoveAllActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAll;
    private javax.swing.JButton btnAddCat;
    private javax.swing.JButton btnRemCat;
    private javax.swing.JButton btnRemoveAll;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JList lstBaseCat;
    private javax.swing.JList lstCategorias;
    private javax.swing.JRadioButton rdAberta;
    private javax.swing.JRadioButton rdFechada;
    private javax.swing.ButtonGroup tipoProva;
    private javax.swing.JTextField txtNomeProf;
    private javax.swing.JTextField txtQtdQuestoes;
    // End of variables declaration//GEN-END:variables
}
