/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Negocio.Alternativa;
import Negocio.DAOException;
import Negocio.ItemAval;
import java.awt.event.ItemEvent;
import java.util.Queue;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author Lasaro
 */
public class ItemAvaliacaoPanel extends javax.swing.JPanel {

    /**
     * Creates new form ItemAvaliacaoPanel
     */
    public ItemAvaliacaoPanel() {
        initComponents();
        lblResultado.setVisible(false);
    }

    public ItemAvaliacaoPanel(ItemAval item) throws DAOException, Exception {
        this();
        lblEnumciado.setText(item.getEnumuciado());
        lblComentario.setText(item.getComentario());
        Alternativa a;
        Queue<Alternativa> alts = item.getAlternativas();
        a = alts.poll();
        if (a != null) {
            rdAlt1.setText(a.getTexto());
        } else {
            throw new Exception("Numero de alternativas do item " + item.getIdItemAval() + "é insuficiente.");
        }
        a = alts.poll();
        if (a != null) {
            rdAlt2.setText(a.getTexto());
        } else {
            throw new Exception("Numero de alternativas do item " + item.getIdItemAval() + "é insuficiente.");
        }
        a = alts.poll();
        if (a != null) {
            rdAlt3.setText(a.getTexto());
        } else {
            throw new Exception("Numero de alternativas do item " + item.getIdItemAval() + "é insuficiente.");
        }
        a = alts.poll();
        if (a != null) {
            rdAlt4.setText(a.getTexto());
        } else {
            throw new Exception("Numero de alternativas do item " + item.getIdItemAval() + "é insuficiente.");
        }
        a = alts.poll();
        if (a != null) {
            rdAlt5.setText(a.getTexto());
        } else {
            throw new Exception("Numero de alternativas do item " + item.getIdItemAval() + "é insuficiente.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alternativas = new javax.swing.ButtonGroup();
        lblEnumciado = new javax.swing.JLabel();
        rdAlt1 = new javax.swing.JRadioButton();
        rdAlt2 = new javax.swing.JRadioButton();
        rdAlt3 = new javax.swing.JRadioButton();
        rdAlt4 = new javax.swing.JRadioButton();
        rdAlt5 = new javax.swing.JRadioButton();
        btnConfirmar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        lblComentario = new javax.swing.JLabel();

        lblEnumciado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEnumciado.setText("Texto enumciado");
        lblEnumciado.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        alternativas.add(rdAlt1);
        rdAlt1.setText("texto alternativa 1");
        rdAlt1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ItemAvaliacaoPanel.this.itemStateChanged(evt);
            }
        });

        alternativas.add(rdAlt2);
        rdAlt2.setText("texto alternativa 2");
        rdAlt2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ItemAvaliacaoPanel.this.itemStateChanged(evt);
            }
        });

        alternativas.add(rdAlt3);
        rdAlt3.setText("texto alternativa 3");
        rdAlt3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ItemAvaliacaoPanel.this.itemStateChanged(evt);
            }
        });

        alternativas.add(rdAlt4);
        rdAlt4.setText("texto alternativa 4");
        rdAlt4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ItemAvaliacaoPanel.this.itemStateChanged(evt);
            }
        });

        alternativas.add(rdAlt5);
        rdAlt5.setText("texto alternativa 5");
        rdAlt5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ItemAvaliacaoPanel.this.itemStateChanged(evt);
            }
        });

        btnConfirmar.setText("Confirmar resposta");
        btnConfirmar.setEnabled(false);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblResultado.setText("<html>Resultado: <b style=\"color:red;\">RESPOSTA ERRADA</b>");

        lblComentario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblComentario.setText("Texto comentario");
        lblComentario.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComentario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEnumciado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdAlt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdAlt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdAlt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdAlt4, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(rdAlt5, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResultado)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnumciado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdAlt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdAlt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdAlt3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdAlt4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdAlt5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComentario, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void itemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            btnConfirmar.setEnabled(true);
        }
    }//GEN-LAST:event_itemStateChanged

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        rdAlt1.setEnabled(false);
        rdAlt2.setEnabled(false);
        rdAlt3.setEnabled(false);
        rdAlt4.setEnabled(false);
        rdAlt5.setEnabled(false);
        lblResultado.setVisible(true);
    }//GEN-LAST:event_btnConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup alternativas;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel lblComentario;
    private javax.swing.JLabel lblEnumciado;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton rdAlt1;
    private javax.swing.JRadioButton rdAlt2;
    private javax.swing.JRadioButton rdAlt3;
    private javax.swing.JRadioButton rdAlt4;
    private javax.swing.JRadioButton rdAlt5;
    // End of variables declaration//GEN-END:variables
}
