/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Negocio.Aluno;
import Negocio.DAOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ildevana
 */
public class Login extends javax.swing.JDialog {

    private java.awt.Frame parent;
    private AlunoControler alunoControl;

    /**
     * Creates new form Login
     *
     * @param parent
     * @param modal
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        alunoControl = new AlunoControler();
        initComponents();
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxAluno = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxAluno.setModel(alunoControl.getComboBoxModel());
        add(cbxAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 330, -1));

        jLabel3.setText("Nome:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, 20));

        jLabel4.setText("Selecione seu nome do aluno para entrar");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 210, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OU cadastre-se");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 350, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 130, 10));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 130, 10));

        btnLogin.setText("Entrar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 60, 80, -1));
        add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 350, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            alunoControl.inserirAluno(txtNome.getText());
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso.", "Info", JOptionPane.INFORMATION_MESSAGE);
            cbxAluno.setModel(alunoControl.getComboBoxModel());
        } catch (DAOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        if (cbxAluno.getSelectedItem() != null) {
            SelecaoProva sl = new SelecaoProva(parent, true, (Aluno) cbxAluno.getSelectedItem());
        } else {
            JOptionPane.showMessageDialog(null, "Selecione seus dados de aluno", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbxAluno;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
