/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Negocio.Aluno;
import Negocio.Categoria;
import java.util.List;

/**
 *
 * @author lasaro
 */
public class SelecaoProva extends javax.swing.JDialog {

    private CategoriaController cControl;
    private ProvaController pControl;
    private Aluno aluno;

    /**
     * Creates new form SelecaoProva
     */
    public SelecaoProva(java.awt.Frame parent, boolean modal, Aluno umAluno) {
        super(parent, modal);
        pControl = new ProvaController();
        cControl = new CategoriaController();
        aluno = umAluno;
        initComponents();
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAvaliacoes = new javax.swing.JTable();
        btnFiltrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnRealizarFechada = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRealizarSelec = new javax.swing.JButton();
        txtHash = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        lstBaseCat = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList();
        btnAddCat = new javax.swing.JButton();
        btnRemCat = new javax.swing.JButton();
        btnRemoveAll = new javax.swing.JButton();
        btnAddAll = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Avaliações disponíveis");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        tableAvaliacoes.setModel(pControl.getAvaliacoesAbertas());
        tableAvaliacoes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableAvaliacoes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableAvaliacoes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 31, 440, 150));

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 100, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 830, 10));

        btnRealizarFechada.setText("Realizar prova fechada");
        getContentPane().add(btnRealizarFechada, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 150, -1));

        jLabel2.setText("Hash de prova fechada:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, 20));

        btnRealizarSelec.setText("Realizar selecionada");
        btnRealizarSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarSelecActionPerformed(evt);
            }
        });
        getContentPane().add(btnRealizarSelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 150, -1));
        getContentPane().add(txtHash, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 110, 20));

        lstBaseCat.setModel(cControl.getListModel());
        jScrollPane9.setViewportView(lstBaseCat);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 150, 120));

        lstCategorias.setModel(new ListCategoriaModel());
        jScrollPane6.setViewportView(lstCategorias);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 150, 120));

        btnAddCat.setText(">");
        btnAddCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCatActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 60, 50, -1));

        btnRemCat.setText("<");
        btnRemCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemCatActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 89, 50, -1));

        btnRemoveAll.setText("<<");
        btnRemoveAll.setToolTipText("");
        btnRemoveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 118, 50, -1));

        btnAddAll.setText(">>");
        btnAddAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAllActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 31, 50, -1));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCatActionPerformed
        List selecteds = lstBaseCat.getSelectedValuesList();
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        for (Object object : selecteds) {
            String[] s = object.toString().split("-");
            Categoria c = new Categoria(Integer.parseInt(s[0].trim()), s[1].trim());
            m1.remove(c);
            m2.add(c);
        }
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnAddCatActionPerformed

    private void btnRemCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemCatActionPerformed
        List selecteds = lstCategorias.getSelectedValuesList();
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        for (Object object : selecteds) {
            String[] s = object.toString().split("-");
            Categoria c = new Categoria(Integer.parseInt(s[0].trim()), s[1].trim());
            m1.add(c);
            m2.remove(c);
        }
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnRemCatActionPerformed

    private void btnRealizarSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarSelecActionPerformed
        int row = tableAvaliacoes.getSelectedRow();
        System.out.println("ID:" + tableAvaliacoes.getValueAt(row, 0));
    }//GEN-LAST:event_btnRealizarSelecActionPerformed

    private void btnAddAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAllActionPerformed
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        List<Categoria> cats = m1.getLista();
        m2.addAll(cats);
        m1.removeAll(cats);
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnAddAllActionPerformed

    private void btnRemoveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAllActionPerformed
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        List<Categoria> cats = m2.getLista();
        m1.addAll(cats);
        m2.removeAll(cats);
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnRemoveAllActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        List<Categoria> cats = ((ListCategoriaModel) lstCategorias.getModel()).getLista();
        if (cats.isEmpty()) {
            tableAvaliacoes.setModel(pControl.getAvaliacoesAbertas());
        } else {
            tableAvaliacoes.setModel(pControl.getProvasPorCategorias(cats));
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAll;
    private javax.swing.JButton btnAddCat;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnRealizarFechada;
    private javax.swing.JButton btnRealizarSelec;
    private javax.swing.JButton btnRemCat;
    private javax.swing.JButton btnRemoveAll;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList lstBaseCat;
    private javax.swing.JList lstCategorias;
    private javax.swing.JTable tableAvaliacoes;
    private javax.swing.JTextField txtHash;
    // End of variables declaration//GEN-END:variables
}
