/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Negocio.Categoria;
import java.util.List;

/**
 *
 * @author lasaro
 */
public class SelecaoProva extends javax.swing.JFrame {

    private CategoriaController cControl;
    private ProvaController pControl;

    /**
     * Creates new form SelecaoProva
     */
    public SelecaoProva() {
        pControl = new ProvaController();
        cControl = new CategoriaController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAvaliacoes = new javax.swing.JTable();
        btnFiltrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnRealizarFechada = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRealizarSelec = new javax.swing.JButton();
        txtHash = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        lstBaseCat = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList();
        btnAddCat = new javax.swing.JButton();
        btnRemCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Avaliações disponíveis");

        tableAvaliacoes.setModel(new ProvaController().getAvaliacoesAbertas());
        tableAvaliacoes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableAvaliacoes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableAvaliacoes);

        btnFiltrar.setText("Filtrar");

        btnRealizarFechada.setText("Realizar prova fechada");

        jLabel2.setText("Hash de prova fechada:");

        btnRealizarSelec.setText("Realizar selecionada");
        btnRealizarSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarSelecActionPerformed(evt);
            }
        });

        lstBaseCat.setModel(cControl.getListModel());
        jScrollPane9.setViewportView(lstBaseCat);

        lstCategorias.setModel(new ListCategoriaModel());
        jScrollPane6.setViewportView(lstCategorias);

        btnAddCat.setText(">");
        btnAddCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCatActionPerformed(evt);
            }
        });

        btnRemCat.setText("<");
        btnRemCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemCat)
                                    .addComponent(btnAddCat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHash, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRealizarFechada))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRealizarSelec)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddCat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemCat))
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiltrar)
                    .addComponent(btnRealizarSelec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRealizarFechada)
                    .addComponent(jLabel2)
                    .addComponent(txtHash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCatActionPerformed
        List selecteds = lstBaseCat.getSelectedValuesList();
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        for (Object object : selecteds) {
            String[] s = object.toString().split("-");
            Categoria c = new Categoria(Integer.parseInt(s[0].trim()), s[1].trim());
            m1.remove(c);
            m2.add(c);
        }
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnAddCatActionPerformed

    private void btnRemCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemCatActionPerformed
        List selecteds = lstCategorias.getSelectedValuesList();
        ListCategoriaModel m1 = (ListCategoriaModel) lstBaseCat.getModel();
        ListCategoriaModel m2 = (ListCategoriaModel) lstCategorias.getModel();
        for (Object object : selecteds) {
            String[] s = object.toString().split("-");
            Categoria c = new Categoria(Integer.parseInt(s[0].trim()), s[1].trim());
            m1.add(c);
            m2.remove(c);
        }
        lstBaseCat.setModel(m1);
        lstCategorias.setModel(m2);
    }//GEN-LAST:event_btnRemCatActionPerformed

    private void btnRealizarSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarSelecActionPerformed
        int row = tableAvaliacoes.getSelectedRow();
        System.out.println("ID:" + tableAvaliacoes.getValueAt(row, 0));
    }//GEN-LAST:event_btnRealizarSelecActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCat;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnRealizarFechada;
    private javax.swing.JButton btnRealizarSelec;
    private javax.swing.JButton btnRemCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList lstBaseCat;
    private javax.swing.JList lstCategorias;
    private javax.swing.JTable tableAvaliacoes;
    private javax.swing.JTextField txtHash;
    // End of variables declaration//GEN-END:variables
}
